// SUNTREX — Real Product Catalog
// Source: Huawei Pricing Calculator (24 ADAR shipment)
// Prices: UP+TR+Mg (EUR) = Unit Price + Transport + Margin
// Margin: 30% applied on cost price

const PRODUCTS = [
  // ═══════════════════════════════════════════
  // INVERTERS — String Inverters (Commercial)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-100ktl-m2",
    sku: "SUN2000-100KTL-M2",
    name: "Huawei SUN2000-100KTL-M2 (AFCI)",
    brand: "Huawei",
    category: "inverters",
    subcategory: "string-inverter",
    type: "Commercial",
    power: "100 kW",
    powerKw: 100,
    phases: 3,
    mppt: 10,
    price: 3731.93, // UP+TR+Mg EUR
    weight: 98.5,
    warranty: "10 ans (extensible à 25 ans)",
    efficiency: "98.8%",
    protection: "IP66",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    features: ["AFCI intégré", "AI Smart I-V Curve Diagnosis", "Smart String Monitoring", "FusionSolar compatible"],
    image: "https://solar.huawei.com/upload/image/SUN2000-100KTL-M2.png",
    datasheet: "https://solar.huawei.com/download/SUN2000-100KTL-M2-datasheet.pdf",
    stock: 1,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — String Inverters (Small Commercial)  
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-30ktl-m3",
    sku: "SUN2000-30KTL-M3",
    name: "Huawei SUN2000-30KTL-M3",
    brand: "Huawei",
    category: "inverters",
    subcategory: "string-inverter",
    type: "Commercial",
    power: "30 kW",
    powerKw: 30,
    phases: 3,
    mppt: 4,
    price: 1626.15,
    weight: 43,
    warranty: "10 ans",
    efficiency: "98.6%",
    protection: "IP66",
    certifications: ["IEC 62109-1", "IEC 62109-2"],
    features: ["Smart I-V Curve Diagnosis", "AI Powered AFCI", "PID Recovery"],
    image: "https://solar.huawei.com/upload/image/SUN2000-30KTL-M3.png",
    stock: 4,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid (Residential)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-6ktl-l1",
    sku: "SUN2000-6KTL-L1",
    name: "Huawei SUN2000-6KTL-L1",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "6 kW",
    powerKw: 6,
    phases: 1,
    mppt: 2,
    price: 544.87,
    weight: 0,
    warranty: "10 ans",
    efficiency: "97.7%",
    protection: "IP65",
    features: ["Compatible LUNA2000", "Export limitation", "100% unbalanced output"],
    image: "https://solar.huawei.com/upload/image/SUN2000-6KTL-L1.png",
    stock: 6,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-8k-lc0",
    sku: "SUN2000-8K-LC0",
    name: "Huawei SUN2000-8K-LC0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "8 kW",
    powerKw: 8,
    phases: 3,
    mppt: 2,
    price: 725.27,
    weight: 22,
    warranty: "10 ans",
    efficiency: "98.0%",
    protection: "IP65",
    features: ["Compatible LUNA2000", "Backup power", "PID Recovery", "AI Smart Arc Protection"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-10k-lc0",
    sku: "SUN2000-10K-LC0",
    name: "Huawei SUN2000-10K-LC0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "10 kW",
    powerKw: 10,
    phases: 3,
    mppt: 2,
    price: 793.20,
    weight: 19.3,
    warranty: "10 ans",
    efficiency: "98.0%",
    protection: "IP65",
    features: ["Compatible LUNA2000", "Backup power", "PID Recovery"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid MAP0 Series (Residential)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-5k-map0",
    sku: "SUN2000-5K-MAP0",
    name: "Huawei SUN2000-5K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "5 kW",
    powerKw: 5,
    phases: 1,
    mppt: 2,
    price: 799.88,
    weight: 21,
    warranty: "10 ans",
    efficiency: "97.7%",
    protection: "IP65",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power", "FusionSolar App"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-6k-map0",
    sku: "SUN2000-6K-MAP0",
    name: "Huawei SUN2000-6K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "6 kW",
    powerKw: 6,
    phases: 1,
    mppt: 2,
    price: 812.13,
    weight: 21,
    warranty: "10 ans",
    efficiency: "97.7%",
    protection: "IP65",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-8k-map0",
    sku: "SUN2000-8K-MAP0",
    name: "Huawei SUN2000-8K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "8 kW",
    powerKw: 8,
    phases: 1,
    mppt: 2,
    price: 960.23,
    weight: 21,
    warranty: "10 ans",
    efficiency: "97.8%",
    protection: "IP65",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-10k-map0",
    sku: "SUN2000-10K-MAP0",
    name: "Huawei SUN2000-10K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "10 kW",
    powerKw: 10,
    phases: 1,
    mppt: 2,
    price: 1071.59,
    weight: 21,
    warranty: "10 ans",
    efficiency: "97.9%",
    protection: "IP65",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-12k-map0",
    sku: "SUN2000-12K-MAP0",
    name: "Huawei SUN2000-12K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "12 kW",
    powerKw: 12,
    phases: 1,
    mppt: 2,
    price: 1196.31,
    weight: 21,
    warranty: "10 ans",
    efficiency: "98.0%",
    protection: "IP65",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid MB0 Series (3-Phase)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-12k-mb0",
    sku: "SUN2000-12K-MB0",
    name: "Huawei SUN2000-12K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "12 kW",
    powerKw: 12,
    phases: 3,
    mppt: 2,
    price: 1486.96,
    weight: 29,
    warranty: "10 ans",
    efficiency: "98.2%",
    protection: "IP65",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power", "100% unbalanced output"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-15k-mb0",
    sku: "SUN2000-15K-MB0",
    name: "Huawei SUN2000-15K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "15 kW",
    powerKw: 15,
    phases: 3,
    mppt: 2,
    price: 1678.49,
    weight: 29,
    warranty: "10 ans",
    efficiency: "98.2%",
    protection: "IP65",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-17k-mb0",
    sku: "SUN2000-17K-MB0",
    name: "Huawei SUN2000-17K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "17 kW",
    powerKw: 17,
    phases: 3,
    mppt: 2,
    price: 1709.67,
    weight: 29,
    warranty: "10 ans",
    efficiency: "98.3%",
    protection: "IP65",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-20k-mb0",
    sku: "SUN2000-20K-MB0",
    name: "Huawei SUN2000-20K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "20 kW",
    powerKw: 20,
    phases: 3,
    mppt: 2,
    price: 1802.10,
    weight: 22,
    warranty: "10 ans",
    efficiency: "98.4%",
    protection: "IP65",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-25k-mb0",
    sku: "SUN2000-25K-MB0",
    name: "Huawei SUN2000-25K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "25 kW",
    powerKw: 25,
    phases: 3,
    mppt: 2,
    price: 1864.46,
    weight: 25,
    warranty: "10 ans",
    efficiency: "98.5%",
    protection: "IP65",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // BATTERIES — LUNA2000 Energy Storage
  // ═══════════════════════════════════════════
  {
    id: "hw-luna2000-5kw-c0",
    sku: "LUNA2000-5KW-C0",
    name: "Huawei LUNA2000-5kW-C0 Power Module (BMS)",
    brand: "Huawei",
    category: "batteries",
    subcategory: "power-module",
    type: "LFP Battery Controller",
    capacity: "5 kW",
    capacityKwh: 5,
    price: 591.64,
    weight: 13.21,
    warranty: "10 ans",
    chemistry: "LiFePO4",
    dod: "100%",
    cycles: "6000+",
    protection: "IP65",
    features: ["BMS intégré", "Empilable 5-30 kWh", "Compatible SUN2000 hybrides", "Optimisation AI"],
    stock: 50,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-luna2000-5-e0",
    sku: "LUNA2000-5-E0",
    name: "Huawei LUNA2000-5-E0 Battery Module (5 kWh)",
    brand: "Huawei",
    category: "batteries",
    subcategory: "battery-module",
    type: "LFP Battery Module",
    capacity: "5 kWh",
    capacityKwh: 5,
    price: 1424.60,
    weight: 50,
    warranty: "10 ans",
    chemistry: "LiFePO4",
    dod: "100%",
    cycles: "6000+",
    protection: "IP65",
    features: ["Module empilable", "1 à 3 modules par Power Unit", "5-15 kWh par stack"],
    stock: 80,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // OPTIMIZERS
  // ═══════════════════════════════════════════
  {
    id: "hw-merc-1300-p",
    sku: "MERC-1300-P",
    name: "Huawei Optimizer MERC-1300-P (Long Cable)",
    brand: "Huawei",
    category: "optimizers",
    subcategory: "power-optimizer",
    type: "DC Optimizer",
    power: "1300 W",
    price: 93.87,
    weight: 1.21,
    warranty: "25 ans",
    protection: "IP68",
    features: ["Module-level MPPT", "Rapid shutdown", "Long input cable", "Compatible SUN2000"],
    stock: 100,
    minOrder: 10,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // SMART DONGLES — Communication
  // ═══════════════════════════════════════════
  {
    id: "hw-sdongle-a05",
    sku: "SDongleA-05",
    name: "Huawei Smart Dongle A-05 (WiFi)",
    brand: "Huawei",
    category: "accessories",
    subcategory: "communication",
    type: "WiFi Dongle",
    price: 66.03,
    weight: 0.126,
    warranty: "5 ans",
    features: ["WiFi communication", "FusionSolar App compatible", "Plug & Play"],
    stock: 30,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sdongle-b06-eu",
    sku: "SDongleB-06-EU",
    name: "Huawei Smart Dongle B-06 EU (4G/LTE)",
    brand: "Huawei",
    category: "accessories",
    subcategory: "communication",
    type: "4G Dongle",
    price: 129.50,
    weight: 0.163,
    warranty: "5 ans",
    features: ["4G LTE communication", "SIM card slot", "FusionSolar App", "No WiFi needed"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // EV CHARGERS
  // ═══════════════════════════════════════════
  {
    id: "hw-scharger-7ks-s0",
    sku: "SCharger-7KS-S0",
    name: "Huawei SCharger-7KS-S0 (7 kW)",
    brand: "Huawei",
    category: "ev-chargers",
    subcategory: "ac-charger",
    type: "AC Charger",
    power: "7 kW",
    price: 391.19,
    weight: 2,
    warranty: "5 ans",
    protection: "IP65",
    features: ["Smart charging", "Solar surplus charging", "FusionSolar integration", "Type 2"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-scharger-22kt-s0",
    sku: "SCharger-22KT-S0",
    name: "Huawei SCharger-22KT-S0 (22 kW)",
    brand: "Huawei",
    category: "ev-chargers",
    subcategory: "ac-charger",
    type: "AC Charger 3-Phase",
    power: "22 kW",
    price: 414.58,
    weight: 2,
    warranty: "5 ans",
    protection: "IP65",
    features: ["22kW fast charging", "Smart solar surplus", "FusionSolar integration", "Type 2"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // SMART METERS & SENSORS
  // ═══════════════════════════════════════════
  {
    id: "hw-smartps-80ai-t0",
    sku: "SmartPS-80AI-T0",
    name: "Huawei SmartPS-80AI-T0 Three-Phase Sensor",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Sensor",
    price: 93.87,
    weight: 0.96,
    warranty: "5 ans",
    features: ["80A rated current", "Three-phase", "AI powered", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-dtsu666-h250a",
    sku: "DTSU666-H250A/50mA",
    name: "Huawei DTSU666-H 250A/50mA Three-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Meter",
    price: 89.41,
    weight: 0,
    warranty: "5 ans",
    features: ["250A via CT", "Three-phase", "RS485 communication", "DIN rail"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-smartps-250a-t0",
    sku: "SmartPS-250A-T0",
    name: "Huawei SmartPS-250A-T0 Three-Phase Sensor",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Sensor",
    price: 89.41,
    weight: 1.5,
    warranty: "5 ans",
    features: ["250A rated current", "Three-phase", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-smartps-100a-s0",
    sku: "SmartPS-100A-S0",
    name: "Huawei SmartPS-100A-S0 Single-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Single-Phase Smart Meter",
    price: 66.03,
    weight: 1.211,
    warranty: "5 ans",
    features: ["100A rated", "Single-phase", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-ddsu666-h",
    sku: "DDSU666-H",
    name: "Huawei DDSU666-H Single-Phase Smart Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Single-Phase Smart Meter",
    price: 66.03,
    weight: 1.211,
    warranty: "5 ans",
    features: ["Single-phase", "RS485", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-dtsu666-h-100a",
    sku: "DTSU666-H-100A",
    name: "Huawei DTSU666-H 100A Three-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Meter",
    price: 93.87,
    weight: 1.211,
    warranty: "5 ans",
    features: ["100A direct", "Three-phase", "RS485", "DIN rail"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // BACKUP BOXES
  // ═══════════════════════════════════════════
  {
    id: "hw-smartguard-63a-s0",
    sku: "SmartGuard-63A-S0",
    name: "Huawei SmartGuard-63A-S0 Single Phase Backup Box",
    brand: "Huawei",
    category: "accessories",
    subcategory: "backup-box",
    type: "Backup Box Single Phase",
    power: "63A",
    price: 530.39,
    weight: 21.24,
    warranty: "10 ans",
    protection: "IP65",
    features: ["Automatic switchover <10ms", "Single phase", "63A rated", "Compatible LUNA2000"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-smartguard-63a-t0",
    sku: "SmartGuard-63A-T0",
    name: "Huawei SmartGuard-63A-T0 Three Phase Backup Box",
    brand: "Huawei",
    category: "accessories",
    subcategory: "backup-box",
    type: "Backup Box Three Phase",
    power: "63A",
    price: 709.68,
    weight: 25.1,
    warranty: "10 ans",
    protection: "IP65",
    features: ["Automatic switchover <10ms", "Three phase", "63A rated", "Compatible LUNA2000"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // ENERGY MANAGEMENT
  // ═══════════════════════════════════════════
  {
    id: "hw-emma-a02",
    sku: "EMMA-A02",
    name: "Huawei EMMA-A02 Energy Management Assistant",
    brand: "Huawei",
    category: "accessories",
    subcategory: "energy-management",
    type: "Energy Management System",
    price: 317.70,
    weight: 1.25,
    warranty: "5 ans",
    features: ["AI-powered energy management", "Smart scheduling", "EV charger integration", "Heat pump control"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
  },
];

// Category definitions for the catalog
export const CATEGORIES = [
  { id: "all", name: "Tous les produits", icon: "📦" },
  { id: "inverters", name: "Onduleurs", icon: "⚡" },
  { id: "batteries", name: "Stockage", icon: "🔋" },
  { id: "optimizers", name: "Optimiseurs", icon: "📈" },
  { id: "ev-chargers", name: "Bornes de recharge", icon: "🚗" },
  { id: "accessories", name: "Accessoires", icon: "🔧" },
];

// Helper functions
export const getProductsByCategory = (cat) =>
  cat === "all" ? PRODUCTS : PRODUCTS.filter(p => p.category === cat);

export const getProductById = (id) =>
  PRODUCTS.find(p => p.id === id);

export const searchProducts = (query) => {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.sku.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    (p.type && p.type.toLowerCase().includes(q))
  );
};

export const getProductCount = () => PRODUCTS.length;

export const getTotalStock = () =>
  PRODUCTS.reduce((sum, p) => sum + (p.stock || 0), 0);

export default PRODUCTS;
