// SUNTREX — Real Product Catalog
// Source: Huawei Pricing Calculator (24 ADAR shipment)
// Prices: UP+TR+Mg (EUR) = Unit Price + Transport + Margin
// Margin: 30% applied on cost price

const PRODUCTS = [
  // ═══════════════════════════════════════════
  // INVERTERS — String Inverters (Commercial)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-100ktl-m2",
    sku: "SUN2000-100KTL-M2",
    name: "Huawei SUN2000-100KTL-M2 (AFCI)",
    brand: "Huawei",
    category: "inverters",
    subcategory: "string-inverter",
    type: "Commercial",
    power: "100 kW",
    powerKw: 100,
    phases: 3,
    mppt: 10,
    price: 3731.93,
    weight: 98.5,
    warranty: "10 years (extendable to 25)",
    efficiency: "98.8%",
    protection: "IP66",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "High-power 100 kW three-phase string inverter with integrated AFCI for commercial rooftop and ground-mount systems. Features AI-powered Smart I-V Curve Diagnosis for real-time fault detection and string-level monitoring via FusionSolar.",
    features: ["AFCI intégré", "AI Smart I-V Curve Diagnosis", "Smart String Monitoring", "FusionSolar compatible"],
    image: "/products/sun2000-m2-commercial.png",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolarV4%2Fsolar-version2%2Fasia-pacific%2Fau%2Fprofessionals%2Fall-products%2Fresidential%2Fsmart-energy-controller%2FSUN2000-8_10_12_15_17_20KTL-M2.pdf",
    stock: 1,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — String Inverters (Small Commercial)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-30ktl-m3",
    sku: "SUN2000-30KTL-M3",
    name: "Huawei SUN2000-30KTL-M3",
    brand: "Huawei",
    category: "inverters",
    subcategory: "string-inverter",
    type: "Commercial",
    power: "30 kW",
    powerKw: 30,
    phases: 3,
    mppt: 4,
    price: 1626.15,
    weight: 43,
    warranty: "10 years",
    efficiency: "98.6%",
    protection: "IP66",
    certifications: ["IEC 62109-1", "IEC 62109-2"],
    description: "Compact 30 kW three-phase string inverter designed for small commercial installations. Integrates AI-powered AFCI arc-fault protection, Smart I-V Curve Diagnosis for proactive maintenance, and PID recovery technology.",
    features: ["Smart I-V Curve Diagnosis", "AI Powered AFCI", "PID Recovery"],
    image: "/products/sun2000-m3-commercial.png",
    datasheet: "https://solar.huawei.com/-/media/Solar/attachment/pdf/la/datasheet/SUN2000-30-40KTL-M3.pdf",
    stock: 4,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid (Residential)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-6ktl-l1",
    sku: "SUN2000-6KTL-L1",
    name: "Huawei SUN2000-6KTL-L1",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "6 kW",
    powerKw: 6,
    phases: 1,
    mppt: 2,
    price: 544.87,
    weight: 0,
    warranty: "10 years",
    efficiency: "97.7%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Single-phase 6 kW hybrid inverter for residential solar-plus-storage systems. Compatible with LUNA2000 batteries for backup power, with export limitation and 100% unbalanced output capability.",
    features: ["Compatible LUNA2000", "Export limitation", "100% unbalanced output"],
    image: "/products/sun2000-3-10ktl-m1.jpg",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/1e029d00296a4b87a9823fd083db547e.pdf",
    stock: 6,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-8k-lc0",
    sku: "SUN2000-8K-LC0",
    name: "Huawei SUN2000-8K-LC0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "8 kW",
    powerKw: 8,
    phases: 3,
    mppt: 2,
    price: 725.27,
    weight: 22,
    warranty: "10 years",
    efficiency: "98.0%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Three-phase 8 kW hybrid inverter from the LC0 series with built-in backup power functionality. Features PID recovery, AI Smart Arc Protection, and seamless integration with LUNA2000 battery storage.",
    features: ["Compatible LUNA2000", "Backup power", "PID Recovery", "AI Smart Arc Protection"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolarV4%2Fsolar-version2%2Fcommon%2Fprofessionals%2Fall-products%2Fresidential%2Fsmart-energy-controller%2Fdatasheet%2FSUN2000-8_10K-LC0.pdf",
  },
  {
    id: "hw-sun2000-10k-lc0",
    sku: "SUN2000-10K-LC0",
    name: "Huawei SUN2000-10K-LC0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "10 kW",
    powerKw: 10,
    phases: 3,
    mppt: 2,
    price: 793.20,
    weight: 19.3,
    warranty: "10 years",
    efficiency: "98.0%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Three-phase 10 kW hybrid inverter from the LC0 series, ideal for medium residential installations. Supports LUNA2000 battery storage with seamless backup power and PID recovery.",
    features: ["Compatible LUNA2000", "Backup power", "PID Recovery"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolarV4%2Fsolar-version2%2Fcommon%2Fprofessionals%2Fall-products%2Fresidential%2Fsmart-energy-controller%2Fdatasheet%2FSUN2000-8_10K-LC0.pdf",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid MAP0 Series (Residential)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-5k-map0",
    sku: "SUN2000-5K-MAP0",
    name: "Huawei SUN2000-5K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "5 kW",
    powerKw: 5,
    phases: 1,
    mppt: 2,
    price: 799.88,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.7%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Next-generation single-phase 5 kW hybrid inverter from the MAP0 series. Designed for residential self-consumption with LUNA2000 battery backup and full FusionSolar App monitoring.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power", "FusionSolar App"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/d44e17e9bfcf4481b361798f8039ab4d.pdf",
  },
  {
    id: "hw-sun2000-6k-map0",
    sku: "SUN2000-6K-MAP0",
    name: "Huawei SUN2000-6K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "6 kW",
    powerKw: 6,
    phases: 1,
    mppt: 2,
    price: 812.13,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.7%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Single-phase 6 kW MAP0 hybrid inverter for residential installations. Features advanced battery management with LUNA2000 compatibility, backup power support, and seamless FusionSolar monitoring.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/d44e17e9bfcf4481b361798f8039ab4d.pdf",
  },
  {
    id: "hw-sun2000-8k-map0",
    sku: "SUN2000-8K-MAP0",
    name: "Huawei SUN2000-8K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "8 kW",
    powerKw: 8,
    phases: 1,
    mppt: 2,
    price: 960.23,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.8%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Single-phase 8 kW MAP0 hybrid inverter optimized for larger residential systems. Delivers 97.8% peak efficiency with LUNA2000 battery integration and backup power capabilities.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/d44e17e9bfcf4481b361798f8039ab4d.pdf",
  },
  {
    id: "hw-sun2000-10k-map0",
    sku: "SUN2000-10K-MAP0",
    name: "Huawei SUN2000-10K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "10 kW",
    powerKw: 10,
    phases: 1,
    mppt: 2,
    price: 1071.59,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.9%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Top-of-range single-phase 10 kW MAP0 hybrid inverter. Offers maximum power for large residential self-consumption with 97.9% efficiency, LUNA2000 storage compatibility, and full backup functionality.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/d44e17e9bfcf4481b361798f8039ab4d.pdf",
  },
  {
    id: "hw-sun2000-12k-map0",
    sku: "SUN2000-12K-MAP0",
    name: "Huawei SUN2000-12K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "12 kW",
    powerKw: 12,
    phases: 1,
    mppt: 2,
    price: 1196.31,
    weight: 21,
    warranty: "10 years",
    efficiency: "98.0%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Highest-power single-phase MAP0 hybrid inverter at 12 kW, reaching 98.0% peak efficiency. Ideal for large residential systems with high self-consumption and LUNA2000 battery backup.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/d44e17e9bfcf4481b361798f8039ab4d.pdf",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid MB0 Series (3-Phase)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-12k-mb0",
    sku: "SUN2000-12K-MB0",
    name: "Huawei SUN2000-12K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "12 kW",
    powerKw: 12,
    phases: 3,
    mppt: 2,
    price: 1486.96,
    weight: 29,
    warranty: "10 years",
    efficiency: "98.2%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Three-phase 12 kW hybrid inverter from the MB0 series. Features 100% unbalanced output capability, LUNA2000 battery compatibility, and seamless backup power for residential installations.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power", "100% unbalanced output"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/c3ba89c365cb42ce92d9ba3c366253f1.pdf",
  },
  {
    id: "hw-sun2000-15k-mb0",
    sku: "SUN2000-15K-MB0",
    name: "Huawei SUN2000-15K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "15 kW",
    powerKw: 15,
    phases: 3,
    mppt: 2,
    price: 1678.49,
    weight: 29,
    warranty: "10 years",
    efficiency: "98.2%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Three-phase 15 kW MB0 hybrid inverter for mid-size residential and small commercial systems. Supports LUNA2000 storage with backup power and 98.2% maximum efficiency.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/c3ba89c365cb42ce92d9ba3c366253f1.pdf",
  },
  {
    id: "hw-sun2000-17k-mb0",
    sku: "SUN2000-17K-MB0",
    name: "Huawei SUN2000-17K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "17 kW",
    powerKw: 17,
    phases: 3,
    mppt: 2,
    price: 1709.67,
    weight: 29,
    warranty: "10 years",
    efficiency: "98.3%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Three-phase 17 kW MB0 hybrid inverter delivering 98.3% peak efficiency. Ideal for larger residential setups requiring three-phase backup power with LUNA2000 battery integration.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/c3ba89c365cb42ce92d9ba3c366253f1.pdf",
  },
  {
    id: "hw-sun2000-20k-mb0",
    sku: "SUN2000-20K-MB0",
    name: "Huawei SUN2000-20K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "20 kW",
    powerKw: 20,
    phases: 3,
    mppt: 2,
    price: 1802.10,
    weight: 22,
    warranty: "10 years",
    efficiency: "98.4%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "High-power three-phase 20 kW MB0 hybrid inverter with 98.4% efficiency. Designed for large residential or small commercial installations with full LUNA2000 backup capability.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/c3ba89c365cb42ce92d9ba3c366253f1.pdf",
  },
  {
    id: "hw-sun2000-25k-mb0",
    sku: "SUN2000-25K-MB0",
    name: "Huawei SUN2000-25K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "25 kW",
    powerKw: 25,
    phases: 3,
    mppt: 2,
    price: 1864.46,
    weight: 25,
    warranty: "10 years",
    efficiency: "98.5%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "Top-of-range three-phase 25 kW MB0 hybrid inverter achieving 98.5% peak efficiency. The most powerful residential hybrid in the MB0 line, with LUNA2000 storage and backup power support.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/c3ba89c365cb42ce92d9ba3c366253f1.pdf",
  },

  // ═══════════════════════════════════════════
  // BATTERIES — LUNA2000 Energy Storage
  // ═══════════════════════════════════════════
  {
    id: "hw-luna2000-5kw-c0",
    sku: "LUNA2000-5KW-C0",
    name: "Huawei LUNA2000-5kW-C0 Power Module (BMS)",
    brand: "Huawei",
    category: "batteries",
    subcategory: "power-module",
    type: "LFP Battery Controller",
    capacity: "5 kW",
    capacityKwh: 5,
    price: 591.64,
    weight: 13.21,
    warranty: "10 years",
    chemistry: "LiFePO4",
    dod: "100%",
    cycles: "6000+",
    protection: "IP65",
    certifications: ["IEC 62619", "UN 38.3", "IEC 63056"],
    description: "LUNA2000 Power Module with integrated BMS for managing up to 3 battery modules (5-15 kWh per stack). LiFePO4 chemistry with 100% depth of discharge and 6000+ cycle lifetime for maximum durability.",
    features: ["BMS intégré", "Empilable 5-30 kWh", "Compatible SUN2000 hybrides", "Optimisation AI"],
    stock: 50,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/luna2000-battery.png",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolarV4%2Fsolar-version2%2Feurope%2Fro%2Fprofessionals%2Fall-products%2Fproduct%2FLUNA2000-5-10-15-S0%2Fsupport%2FLUNA2000-5-10-15-S0-datasheet.pdf",
  },
  {
    id: "hw-luna2000-5-e0",
    sku: "LUNA2000-5-E0",
    name: "Huawei LUNA2000-5-E0 Battery Module (5 kWh)",
    brand: "Huawei",
    category: "batteries",
    subcategory: "battery-module",
    type: "LFP Battery Module",
    capacity: "5 kWh",
    capacityKwh: 5,
    price: 1424.60,
    weight: 50,
    warranty: "10 years",
    chemistry: "LiFePO4",
    dod: "100%",
    cycles: "6000+",
    protection: "IP65",
    certifications: ["IEC 62619", "UN 38.3", "IEC 63056"],
    description: "5 kWh stackable LiFePO4 battery module for the LUNA2000 system. Supports 1 to 3 modules per Power Unit (5-15 kWh per stack), with 100% DoD and over 6000 cycles for long-term reliability.",
    features: ["Module empilable", "1 à 3 modules par Power Unit", "5-15 kWh par stack"],
    stock: 80,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/luna2000-battery.png",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolarV4%2Fsolar-version2%2Feurope%2Fro%2Fprofessionals%2Fall-products%2Fproduct%2FLUNA2000-5-10-15-S0%2Fsupport%2FLUNA2000-5-10-15-S0-datasheet.pdf",
  },

  // ═══════════════════════════════════════════
  // OPTIMIZERS
  // ═══════════════════════════════════════════
  {
    id: "hw-merc-1300-p",
    sku: "MERC-1300-P",
    name: "Huawei Optimizer MERC-1300-P (Long Cable)",
    brand: "Huawei",
    category: "optimizers",
    subcategory: "power-optimizer",
    type: "DC Optimizer",
    power: "1300 W",
    price: 93.87,
    weight: 1.21,
    warranty: "25 years",
    protection: "IP68",
    certifications: ["IEC 62109-1", "IEC 62109-2"],
    description: "1300 W DC power optimizer with extended input cable for flexible panel layouts. Provides module-level MPPT for maximum energy harvest, rapid shutdown compliance, and compatibility with all SUN2000 string inverters.",
    features: ["Module-level MPPT", "Rapid shutdown", "Long input cable", "Compatible SUN2000"],
    stock: 100,
    minOrder: 10,
    seller: "QUALIWATT",
    image: "/products/sun2000-450w-p2.png",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/422945b897cd4c1fb5ce16e2c7931240.pdf",
  },

  // ═══════════════════════════════════════════
  // SMART DONGLES — Communication
  // ═══════════════════════════════════════════
  {
    id: "hw-sdongle-a05",
    sku: "SDongleA-05",
    name: "Huawei Smart Dongle A-05 (WiFi)",
    brand: "Huawei",
    category: "accessories",
    subcategory: "communication",
    type: "WiFi Dongle",
    price: 66.03,
    weight: 0.126,
    warranty: "5 years",
    certifications: ["CE"],
    description: "Compact WiFi communication dongle for connecting Huawei inverters to the FusionSolar monitoring platform. Plug-and-play installation with automatic firmware updates and real-time system monitoring.",
    features: ["WiFi communication", "FusionSolar App compatible", "Plug & Play"],
    stock: 30,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/smartdongle-wlan.png",
    datasheet: "https://solar.huawei.com/-/media/Solar/attachment/pdf/mea/datasheet/SmartDongle-WLAN-FE.pdf",
  },
  {
    id: "hw-sdongle-b06-eu",
    sku: "SDongleB-06-EU",
    name: "Huawei Smart Dongle B-06 EU (4G/LTE)",
    brand: "Huawei",
    category: "accessories",
    subcategory: "communication",
    type: "4G Dongle",
    price: 129.50,
    weight: 0.163,
    warranty: "5 years",
    certifications: ["CE", "RED"],
    description: "4G/LTE communication dongle with SIM card slot for remote monitoring without WiFi infrastructure. Ideal for rural or commercial installations where WiFi is unavailable, with full FusionSolar App integration.",
    features: ["4G LTE communication", "SIM card slot", "FusionSolar App", "No WiFi needed"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/smartdongle-4g.png",
    datasheet: "https://support.huawei.com/enterprise/en/doc/EDOC1100253102",
  },

  // ═══════════════════════════════════════════
  // EV CHARGERS
  // ═══════════════════════════════════════════
  {
    id: "hw-scharger-7ks-s0",
    sku: "SCharger-7KS-S0",
    name: "Huawei SCharger-7KS-S0 (7 kW)",
    brand: "Huawei",
    category: "ev-chargers",
    subcategory: "ac-charger",
    type: "AC Charger",
    power: "7 kW",
    price: 391.19,
    weight: 2,
    warranty: "5 years",
    protection: "IP65",
    certifications: ["IEC 61851-1", "IEC 62196-2"],
    description: "7 kW single-phase AC EV charger with Type 2 connector. Features intelligent solar surplus charging via FusionSolar integration, maximizing self-consumption from your PV system.",
    features: ["Smart charging", "Solar surplus charging", "FusionSolar integration", "Type 2"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-scharger-7k.svg",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/a1adf14392d644c1b432f62ea10fa0ff.pdf",
  },
  {
    id: "hw-scharger-22kt-s0",
    sku: "SCharger-22KT-S0",
    name: "Huawei SCharger-22KT-S0 (22 kW)",
    brand: "Huawei",
    category: "ev-chargers",
    subcategory: "ac-charger",
    type: "AC Charger 3-Phase",
    power: "22 kW",
    price: 414.58,
    weight: 2,
    warranty: "5 years",
    protection: "IP65",
    certifications: ["IEC 61851-1", "IEC 62196-2"],
    description: "22 kW three-phase AC EV charger delivering fast charging speeds with Type 2 connector. Smart solar surplus mode prioritizes PV energy for vehicle charging through FusionSolar integration.",
    features: ["22kW fast charging", "Smart solar surplus", "FusionSolar integration", "Type 2"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-scharger-22k.svg",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/a1adf14392d644c1b432f62ea10fa0ff.pdf",
  },

  // ═══════════════════════════════════════════
  // SMART METERS & SENSORS
  // ═══════════════════════════════════════════
  {
    id: "hw-smartps-80ai-t0",
    sku: "SmartPS-80AI-T0",
    name: "Huawei SmartPS-80AI-T0 Three-Phase Sensor",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Sensor",
    price: 93.87,
    weight: 0.96,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11"],
    description: "AI-powered three-phase 80A smart power sensor with DIN rail mounting. Provides accurate real-time energy measurement for grid export/import monitoring and optimal inverter control.",
    features: ["80A rated current", "Three-phase", "AI powered", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smart-pwr-sensor.svg",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/79676c3a0de542bf8e6ff9da6d177138.pdf",
  },
  {
    id: "hw-dtsu666-h250a",
    sku: "DTSU666-H250A/50mA",
    name: "Huawei DTSU666-H 250A/50mA Three-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Meter",
    price: 89.41,
    weight: 0,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11", "IEC 62053-21"],
    description: "Three-phase smart energy meter with 250A measurement via external CTs (50mA secondary). RS485 communication for seamless integration with Huawei inverters and FusionSolar monitoring.",
    features: ["250A via CT", "Three-phase", "RS485 communication", "DIN rail"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-dtsu666-h.svg",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolar%2Fdatasheet%2FDTSU666-H.pdf",
  },
  {
    id: "hw-smartps-250a-t0",
    sku: "SmartPS-250A-T0",
    name: "Huawei SmartPS-250A-T0 Three-Phase Sensor",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Sensor",
    price: 89.41,
    weight: 1.5,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11"],
    description: "Three-phase 250A smart power sensor for high-current commercial installations. DIN rail mounted with RS485 interface for accurate bidirectional energy measurement.",
    features: ["250A rated current", "Three-phase", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smart-sensor-1000a.svg",
    datasheet: "https://midsummer.ie/pdfs/datasheet-smartps-250a-t0-en.pdf",
  },
  {
    id: "hw-smartps-100a-s0",
    sku: "SmartPS-100A-S0",
    name: "Huawei SmartPS-100A-S0 Single-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Single-Phase Smart Meter",
    price: 66.03,
    weight: 1.211,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11"],
    description: "Single-phase 100A smart power sensor for residential grid metering. Compact DIN rail design with precise bidirectional energy measurement for export limitation and self-consumption optimization.",
    features: ["100A rated", "Single-phase", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smart-sensor-300a.svg",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolar%2Fdatasheet%2FSmartPS-100A-S0.pdf",
  },
  {
    id: "hw-ddsu666-h",
    sku: "DDSU666-H",
    name: "Huawei DDSU666-H Single-Phase Smart Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Single-Phase Smart Meter",
    price: 66.03,
    weight: 1.211,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11", "IEC 62053-21"],
    description: "Single-phase smart energy meter with RS485 communication for direct connection to Huawei inverters. DIN rail mounted for easy installation in residential distribution boards.",
    features: ["Single-phase", "RS485", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-ddsu666-h.svg",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolar%2Fdatasheet%2FDDSU666-H.pdf",
  },
  {
    id: "hw-dtsu666-h-100a",
    sku: "DTSU666-H-100A",
    name: "Huawei DTSU666-H 100A Three-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Meter",
    price: 93.87,
    weight: 1.211,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11", "IEC 62053-21"],
    description: "Three-phase 100A direct-connection smart meter with RS485 interface. Provides precise bidirectional energy measurement for grid monitoring, export control, and FusionSolar analytics.",
    features: ["100A direct", "Three-phase", "RS485", "DIN rail"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-dtsu666-h.svg",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolar%2Fdatasheet%2FDTSU666-H.pdf",
  },

  // ═══════════════════════════════════════════
  // BACKUP BOXES
  // ═══════════════════════════════════════════
  {
    id: "hw-smartguard-63a-s0",
    sku: "SmartGuard-63A-S0",
    name: "Huawei SmartGuard-63A-S0 Single Phase Backup Box",
    brand: "Huawei",
    category: "accessories",
    subcategory: "backup-box",
    type: "Backup Box Single Phase",
    power: "63A",
    price: 530.39,
    weight: 21.24,
    warranty: "10 years",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 60947-6-1"],
    description: "Single-phase 63A automatic backup box with <10ms switchover time for seamless transition to battery power during grid outages. IP65 rated for indoor/outdoor installation, compatible with LUNA2000 storage.",
    features: ["Automatic switchover <10ms", "Single phase", "63A rated", "Compatible LUNA2000"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smartguard-1ph.svg",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolar%2Fdatasheet%2FSmartGuard-63A-S0.pdf",
  },
  {
    id: "hw-smartguard-63a-t0",
    sku: "SmartGuard-63A-T0",
    name: "Huawei SmartGuard-63A-T0 Three Phase Backup Box",
    brand: "Huawei",
    category: "accessories",
    subcategory: "backup-box",
    type: "Backup Box Three Phase",
    power: "63A",
    price: 709.68,
    weight: 25.1,
    warranty: "10 years",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 60947-6-1"],
    description: "Three-phase 63A automatic backup box providing <10ms switchover for uninterrupted power supply during grid failures. Designed for three-phase residential systems with LUNA2000 battery storage.",
    features: ["Automatic switchover <10ms", "Three phase", "63A rated", "Compatible LUNA2000"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smartguard-3ph.svg",
    datasheet: "https://solar.huawei.com/admin/asset/v1/pro/view/fae1d0d46364459191f51ff78db88c3b.pdf",
  },

  // ═══════════════════════════════════════════
  // ENERGY MANAGEMENT
  // ═══════════════════════════════════════════
  {
    id: "hw-emma-a02",
    sku: "EMMA-A02",
    name: "Huawei EMMA-A02 Energy Management Assistant",
    brand: "Huawei",
    category: "accessories",
    subcategory: "energy-management",
    type: "Energy Management System",
    price: 317.70,
    weight: 1.25,
    warranty: "5 years",
    certifications: ["CE", "RED"],
    description: "AI-powered energy management assistant that intelligently schedules energy flows between PV, battery, EV charger, heat pump, and grid. Maximizes self-consumption and minimizes electricity costs through smart load balancing.",
    features: ["AI-powered energy management", "Smart scheduling", "EV charger integration", "Heat pump control"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-emma-a02.svg",
    datasheet: "https://solar.huawei.com/download?p=%2F-%2Fmedia%2FSolar%2Fdatasheet%2FEMMA-A02.pdf",
  },
];

// Category definitions for the catalog
export const CATEGORIES = [
  { id: "all", name: "Tous les produits", icon: "📦" },
  { id: "inverters", name: "Onduleurs", icon: "⚡" },
  { id: "batteries", name: "Stockage", icon: "🔋" },
  { id: "optimizers", name: "Optimiseurs", icon: "📈" },
  { id: "ev-chargers", name: "Bornes de recharge", icon: "🚗" },
  { id: "accessories", name: "Accessoires", icon: "🔧" },
];

// Helper functions
export const getProductsByCategory = (cat) =>
  cat === "all" ? PRODUCTS : PRODUCTS.filter(p => p.category === cat);

export const getProductById = (id) =>
  PRODUCTS.find(p => p.id === id);

export const searchProducts = (query) => {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.sku.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    (p.type && p.type.toLowerCase().includes(q))
  );
};

export const getProductCount = () => PRODUCTS.length;

export const getTotalStock = () =>
  PRODUCTS.reduce((sum, p) => sum + (p.stock || 0), 0);

export default PRODUCTS;
