// SUNTREX — Real Product Catalog
// Source: Huawei Pricing Calculator (24 ADAR shipment)
// Prices: UP+TR+Mg (EUR) = Unit Price + Transport + Margin
// Margin: 30% applied on cost price

const PRODUCTS = [
  // ═══════════════════════════════════════════
  // INVERTERS — String Inverters (Commercial)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-100ktl-m2",
    sku: "SUN2000-100KTL-M2",
    name: "Huawei SUN2000-100KTL-M2 (AFCI)",
    brand: "Huawei",
    category: "inverters",
    subcategory: "string-inverter",
    type: "Commercial",
    power: "100 kW",
    powerKw: 100,
    phases: 3,
    mppt: 10,
    price: 3731.93,
    weight: 98.5,
    warranty: "10 years (extendable to 25)",
    efficiency: "98.8%",
    protection: "IP66",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-100KTL-M2 is Huawei's flagship 100 kW three-phase string inverter, engineered for large-scale commercial rooftop and ground-mount PV systems. It delivers industry-leading 98.8% maximum efficiency with 10 independent MPPTs for optimal energy harvest across complex roof layouts and partial shading conditions. Integrated AFCI (Arc Fault Circuit Interrupter) provides proactive fire safety, while AI-powered Smart I-V Curve Diagnosis enables real-time string-level fault detection without manual inspection. IP66-rated for harsh outdoor environments, it supports Smart String Monitoring via FusionSolar for complete plant visibility and predictive O&M.",
    features: ["AFCI intégré", "AI Smart I-V Curve Diagnosis", "Smart String Monitoring", "FusionSolar compatible"],
    image: "/products/sun2000-m2-commercial.png",
    datasheet: "/datasheets/sun2000-100ktl-m2.pdf",
    stock: 1,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — String Inverters (Small Commercial)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-30ktl-m3",
    sku: "SUN2000-30KTL-M3",
    name: "Huawei SUN2000-30KTL-M3",
    brand: "Huawei",
    category: "inverters",
    subcategory: "string-inverter",
    type: "Commercial",
    power: "30 kW",
    powerKw: 30,
    phases: 3,
    mppt: 4,
    price: 1626.15,
    weight: 43,
    warranty: "10 years",
    efficiency: "98.6%",
    protection: "IP66",
    certifications: ["IEC 62109-1", "IEC 62109-2"],
    description: "The SUN2000-30KTL-M3 is a compact 30 kW three-phase string inverter optimized for small commercial and industrial rooftop installations. With 98.6% peak efficiency and 4 MPPTs, it maximizes yield on multi-orientation roofs while maintaining a lightweight 43 kg form factor for easy one-person installation. AI-powered AFCI arc-fault detection ensures fire safety compliance, and Smart I-V Curve Diagnosis automatically identifies underperforming strings for proactive maintenance. Built-in PID recovery technology restores module performance degraded by potential-induced degradation. IP66-rated with natural convection cooling for silent, maintenance-free operation.",
    features: ["Smart I-V Curve Diagnosis", "AI Powered AFCI", "PID Recovery"],
    image: "/products/sun2000-m3-commercial.png",
    datasheet: "/datasheets/sun2000-30ktl-m3.pdf",
    stock: 4,
    minOrder: 1,
    seller: "QUALIWATT",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid (Residential)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-6ktl-l1",
    sku: "SUN2000-6KTL-L1",
    name: "Huawei SUN2000-6KTL-L1",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "6 kW",
    powerKw: 6,
    phases: 1,
    mppt: 2,
    price: 544.87,
    weight: 0,
    warranty: "10 years",
    efficiency: "97.7%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-6KTL-L1 is a single-phase 6 kW hybrid inverter designed for residential solar-plus-storage systems in single-phase grid configurations. It supports seamless integration with LUNA2000 LiFePO4 batteries for energy storage and backup power, with intelligent export limitation to comply with grid feed-in regulations. The 100% unbalanced output capability ensures stable operation even with asymmetric loads. With 97.7% peak efficiency, 2 MPPTs for flexible string design, and IP65 protection for indoor/outdoor mounting, it is the ideal entry point for Huawei's residential energy ecosystem.",
    features: ["Compatible LUNA2000", "Export limitation", "100% unbalanced output"],
    image: "/products/sun2000-3-10ktl-m1.jpg",
    datasheet: "/datasheets/sun2000-6ktl-l1.pdf",
    stock: 6,
    minOrder: 1,
    seller: "QUALIWATT",
  },
  {
    id: "hw-sun2000-8k-lc0",
    sku: "SUN2000-8K-LC0",
    name: "Huawei SUN2000-8K-LC0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "8 kW",
    powerKw: 8,
    phases: 3,
    mppt: 2,
    price: 725.27,
    weight: 22,
    warranty: "10 years",
    efficiency: "98.0%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-8K-LC0 is a three-phase 8 kW hybrid inverter from Huawei's latest LC0 series, purpose-built for residential energy independence. It delivers 98.0% maximum efficiency with 2 MPPTs and features built-in backup power functionality for seamless transition to battery supply during grid outages. AI Smart Arc Protection (AFCI) provides continuous fire safety monitoring, while PID recovery technology automatically restores degraded module performance overnight. Compatible with LUNA2000 batteries (up to 30 kWh) and SmartGuard backup boxes for whole-home backup. IP65-rated for flexible indoor or outdoor installation.",
    features: ["Compatible LUNA2000", "Backup power", "PID Recovery", "AI Smart Arc Protection"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "/datasheets/sun2000-8k-10k-lc0.pdf",
  },
  {
    id: "hw-sun2000-10k-lc0",
    sku: "SUN2000-10K-LC0",
    name: "Huawei SUN2000-10K-LC0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "10 kW",
    powerKw: 10,
    phases: 3,
    mppt: 2,
    price: 793.20,
    weight: 19.3,
    warranty: "10 years",
    efficiency: "98.0%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-10K-LC0 is a three-phase 10 kW hybrid inverter from Huawei's LC0 series, ideal for medium to large residential installations requiring three-phase grid connection. With 98.0% peak efficiency and 2 MPPTs, it provides optimal energy harvest while supporting LUNA2000 battery storage for self-consumption maximization and backup power. Integrated PID recovery automatically restores module degradation, and the compact 19.3 kg design enables easy wall-mounting. Fully compatible with SmartGuard backup boxes for up to 15 kW whole-home backup power during grid outages. IP65-rated with FusionSolar monitoring for real-time energy flow visualization.",
    features: ["Compatible LUNA2000", "Backup power", "PID Recovery"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "/datasheets/sun2000-8k-10k-lc0.pdf",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid MAP0 Series (Residential)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-5k-map0",
    sku: "SUN2000-5K-MAP0",
    name: "Huawei SUN2000-5K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "5 kW",
    powerKw: 5,
    phases: 1,
    mppt: 2,
    price: 799.88,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.7%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-5K-MAP0 is Huawei's next-generation single-phase 5 kW hybrid inverter from the MAP0 series, representing a major leap in residential energy management. It features an integrated high-frequency isolation transformer for enhanced safety, 2 MPPTs for flexible string design, and native LUNA2000 battery compatibility for seamless solar-plus-storage operation. The MAP0 architecture delivers faster MPPT response for superior performance under dynamic shading conditions. With FusionSolar App integration, homeowners get real-time energy flow monitoring, smart charging scheduling, and AI-optimized self-consumption. IP65-rated for indoor and outdoor installation with natural convection cooling.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power", "FusionSolar App"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "/datasheets/sun2000-map0-series.pdf",
  },
  {
    id: "hw-sun2000-6k-map0",
    sku: "SUN2000-6K-MAP0",
    name: "Huawei SUN2000-6K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "6 kW",
    powerKw: 6,
    phases: 1,
    mppt: 2,
    price: 812.13,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.7%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-6K-MAP0 is a single-phase 6 kW hybrid inverter from Huawei's advanced MAP0 series, optimized for medium residential self-consumption systems. It combines 97.7% peak efficiency with intelligent battery management for LUNA2000 LiFePO4 storage, enabling time-of-use optimization and backup power during grid outages. The MAP0 platform features an upgraded MPPT algorithm with faster response to shading transients, maximizing energy yield throughout the day. Full integration with FusionSolar provides remote monitoring, firmware updates, and AI-driven energy scheduling. IP65-rated with a compact form factor for flexible wall-mount installation.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "/datasheets/sun2000-map0-series.pdf",
  },
  {
    id: "hw-sun2000-8k-map0",
    sku: "SUN2000-8K-MAP0",
    name: "Huawei SUN2000-8K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "8 kW",
    powerKw: 8,
    phases: 1,
    mppt: 2,
    price: 960.23,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.8%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-8K-MAP0 is a single-phase 8 kW hybrid inverter from the MAP0 series, designed for larger residential systems with high electricity consumption. It delivers 97.8% peak efficiency and supports up to 30 kWh of LUNA2000 battery storage for maximum self-consumption and backup power capability. The advanced MAP0 MPPT algorithm ensures superior energy harvest even under challenging shading conditions, while integrated AFCI arc-fault detection provides continuous fire safety monitoring. Supports smart export limitation for grid compliance and seamless integration with Huawei's SCharger EV chargers for solar-powered vehicle charging.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "/datasheets/sun2000-map0-series.pdf",
  },
  {
    id: "hw-sun2000-10k-map0",
    sku: "SUN2000-10K-MAP0",
    name: "Huawei SUN2000-10K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "10 kW",
    powerKw: 10,
    phases: 1,
    mppt: 2,
    price: 1071.59,
    weight: 21,
    warranty: "10 years",
    efficiency: "97.9%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-10K-MAP0 is the most powerful single-phase hybrid inverter in Huawei's MAP0 lineup, delivering 10 kW at 97.9% peak efficiency for large residential systems. It supports up to 30 kWh of LUNA2000 battery storage and provides full backup power capability via SmartGuard integration for uninterrupted supply during grid outages. The MAP0 platform's advanced MPPT tracking algorithm maximizes yield under partial shading, while built-in AFCI and PID recovery ensure long-term safety and performance. Ideal for high-consumption households with EV charging, heat pumps, and air conditioning loads.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "/datasheets/sun2000-map0-series.pdf",
  },
  {
    id: "hw-sun2000-12k-map0",
    sku: "SUN2000-12K-MAP0",
    name: "Huawei SUN2000-12K-MAP0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid",
    power: "12 kW",
    powerKw: 12,
    phases: 1,
    mppt: 2,
    price: 1196.31,
    weight: 21,
    warranty: "10 years",
    efficiency: "98.0%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-12K-MAP0 is Huawei's highest-power single-phase hybrid inverter, delivering 12 kW at an industry-leading 98.0% efficiency for maximum residential energy production. Designed for large homes with significant energy demands, it supports up to 30 kWh of LUNA2000 battery storage and full backup power with SmartGuard integration. The MAP0 architecture features enhanced MPPT response for optimal performance under dynamic shading, AI-powered energy scheduling via EMMA integration, and comprehensive safety features including AFCI and residual current monitoring. Perfect for self-consumption optimization with EV chargers, heat pumps, and smart home systems.",
    features: ["New MAP0 series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-m5-hybrid.png",
    datasheet: "/datasheets/sun2000-map0-series.pdf",
  },

  // ═══════════════════════════════════════════
  // INVERTERS — Hybrid MB0 Series (3-Phase)
  // ═══════════════════════════════════════════
  {
    id: "hw-sun2000-12k-mb0",
    sku: "SUN2000-12K-MB0",
    name: "Huawei SUN2000-12K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "12 kW",
    powerKw: 12,
    phases: 3,
    mppt: 2,
    price: 1486.96,
    weight: 29,
    warranty: "10 years",
    efficiency: "98.2%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-12K-MB0 is the entry model in Huawei's three-phase MB0 hybrid inverter series, delivering 12 kW at 98.2% peak efficiency for residential installations with three-phase grid connection. It features 100% unbalanced output capability for stable operation with asymmetric loads, and supports up to 30 kWh of LUNA2000 battery storage for self-consumption maximization. Integrated backup power via SmartGuard ensures whole-home supply during grid outages with <10ms switchover. The MB0 series introduces an upgraded power module with higher power density, active arcing protection, and enhanced grid support functions including reactive power compensation.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power", "100% unbalanced output"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "/datasheets/sun2000-mb0-series.pdf",
  },
  {
    id: "hw-sun2000-15k-mb0",
    sku: "SUN2000-15K-MB0",
    name: "Huawei SUN2000-15K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "15 kW",
    powerKw: 15,
    phases: 3,
    mppt: 2,
    price: 1678.49,
    weight: 29,
    warranty: "10 years",
    efficiency: "98.2%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-15K-MB0 is a three-phase 15 kW hybrid inverter from Huawei's MB0 series, designed for mid-size residential and small commercial applications. It delivers 98.2% peak efficiency with 2 MPPTs and supports LUNA2000 battery storage up to 30 kWh for comprehensive energy management. The MB0 platform provides 100% unbalanced output, active arcing protection (AFCI), and full backup power capability via SmartGuard integration. Compatible with EMMA energy management assistant for AI-driven optimization of PV, battery, EV charger, and heat pump loads. IP65-rated for indoor/outdoor installation with silent natural convection cooling.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "/datasheets/sun2000-mb0-series.pdf",
  },
  {
    id: "hw-sun2000-17k-mb0",
    sku: "SUN2000-17K-MB0",
    name: "Huawei SUN2000-17K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "17 kW",
    powerKw: 17,
    phases: 3,
    mppt: 2,
    price: 1709.67,
    weight: 29,
    warranty: "10 years",
    efficiency: "98.3%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-17K-MB0 is a three-phase 17 kW hybrid inverter delivering 98.3% peak efficiency, positioned for larger European residential homes with three-phase supply. It features 2 MPPTs, 100% unbalanced output, and supports up to 30 kWh of LUNA2000 storage for time-of-use optimization and backup power. Integrated AFCI arc-fault detection and PID recovery ensure long-term safety and performance, while SmartGuard compatibility enables whole-home backup during grid failures. Full FusionSolar integration provides real-time monitoring, remote diagnostics, and AI-powered energy scheduling through EMMA.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "/datasheets/sun2000-mb0-series.pdf",
  },
  {
    id: "hw-sun2000-20k-mb0",
    sku: "SUN2000-20K-MB0",
    name: "Huawei SUN2000-20K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "20 kW",
    powerKw: 20,
    phases: 3,
    mppt: 2,
    price: 1802.10,
    weight: 22,
    warranty: "10 years",
    efficiency: "98.4%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-20K-MB0 is a high-power three-phase 20 kW hybrid inverter achieving 98.4% peak efficiency, ideal for large residential villas and small commercial installations. The compact 22 kg design belies its powerful performance, with 2 MPPTs, 100% unbalanced output, and up to 30 kWh LUNA2000 battery support. Full backup power capability via SmartGuard integration ensures uninterrupted supply for critical loads during grid outages. Advanced safety features include AI-powered AFCI, residual current monitoring, and surge protection. Seamlessly integrates with Huawei's complete ecosystem including SCharger EV chargers, EMMA energy management, and FusionSolar cloud monitoring.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "/datasheets/sun2000-mb0-series.pdf",
  },
  {
    id: "hw-sun2000-25k-mb0",
    sku: "SUN2000-25K-MB0",
    name: "Huawei SUN2000-25K-MB0",
    brand: "Huawei",
    category: "inverters",
    subcategory: "hybrid-inverter",
    type: "Hybrid 3-Phase",
    power: "25 kW",
    powerKw: 25,
    phases: 3,
    mppt: 2,
    price: 1864.46,
    weight: 25,
    warranty: "10 years",
    efficiency: "98.5%",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 62109-2", "EN 50549-1"],
    description: "The SUN2000-25K-MB0 is the flagship of Huawei's three-phase MB0 hybrid series, delivering 25 kW at an exceptional 98.5% peak efficiency — the highest in its class. Designed for large residential estates and small commercial installations, it supports up to 30 kWh of LUNA2000 battery storage with full backup power via SmartGuard. The MB0 architecture features 100% unbalanced output for maximum flexibility, AI-powered AFCI for continuous fire safety, and PID recovery for long-term module health. With EMMA integration, it intelligently orchestrates PV generation, battery storage, EV charging, and heat pump operation to minimize grid dependency and electricity costs.",
    features: ["MB0 3-phase series", "Compatible LUNA2000", "Backup power"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/sun2000-10ktl-m2.png",
    datasheet: "/datasheets/sun2000-mb0-series.pdf",
  },

  // ═══════════════════════════════════════════
  // BATTERIES — LUNA2000 Energy Storage
  // ═══════════════════════════════════════════
  {
    id: "hw-luna2000-5kw-c0",
    sku: "LUNA2000-5KW-C0",
    name: "Huawei LUNA2000-5kW-C0 Power Module (BMS)",
    brand: "Huawei",
    category: "batteries",
    subcategory: "power-module",
    type: "LFP Battery Controller",
    capacity: "5 kW",
    capacityKwh: 5,
    price: 591.64,
    weight: 13.21,
    warranty: "10 years",
    chemistry: "LiFePO4",
    dod: "100%",
    cycles: "6000+",
    protection: "IP65",
    certifications: ["IEC 62619", "UN 38.3", "IEC 63056"],
    description: "The LUNA2000-5kW-C0 is Huawei's intelligent Power Module with integrated Battery Management System (BMS), serving as the brain of the LUNA2000 residential energy storage system. It manages up to 3 battery modules per stack (5-15 kWh) with advanced cell-level monitoring, thermal management, and charge/discharge optimization. The LiFePO4 chemistry delivers unmatched safety with 100% depth of discharge and over 6000 cycle lifetime, backed by Huawei's 10-year warranty. AI-powered algorithms optimize charging patterns based on weather forecasts, electricity tariffs, and household consumption patterns. Supports cascading up to 2 stacks (30 kWh total) for maximum energy independence.",
    features: ["BMS intégré", "Empilable 5-30 kWh", "Compatible SUN2000 hybrides", "Optimisation AI"],
    stock: 50,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/luna2000-battery.png",
    datasheet: "/datasheets/luna2000-s0.pdf",
  },
  {
    id: "hw-luna2000-5-e0",
    sku: "LUNA2000-5-E0",
    name: "Huawei LUNA2000-5-E0 Battery Module (5 kWh)",
    brand: "Huawei",
    category: "batteries",
    subcategory: "battery-module",
    type: "LFP Battery Module",
    capacity: "5 kWh",
    capacityKwh: 5,
    price: 1424.60,
    weight: 50,
    warranty: "10 years",
    chemistry: "LiFePO4",
    dod: "100%",
    cycles: "6000+",
    protection: "IP65",
    certifications: ["IEC 62619", "UN 38.3", "IEC 63056"],
    description: "The LUNA2000-5-E0 is a 5 kWh stackable LiFePO4 battery module that extends the capacity of any LUNA2000 energy storage system. Each Power Module (C0) supports 1 to 3 battery modules, enabling flexible 5-15 kWh configurations per stack. The prismatic LiFePO4 cells deliver exceptional thermal stability and safety, with 100% usable depth of discharge and over 6000 charge cycles for a 15+ year operational lifetime. The modular plug-and-play design allows capacity expansion without rewiring — simply stack additional modules. IP65-rated with integrated fire safety barriers between modules for residential peace of mind.",
    features: ["Module empilable", "1 à 3 modules par Power Unit", "5-15 kWh par stack"],
    stock: 80,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/luna2000-battery.png",
    datasheet: "/datasheets/luna2000-s0.pdf",
  },

  // ═══════════════════════════════════════════
  // OPTIMIZERS
  // ═══════════════════════════════════════════
  {
    id: "hw-merc-1300-p",
    sku: "MERC-1300-P",
    name: "Huawei Optimizer MERC-1300-P (Long Cable)",
    brand: "Huawei",
    category: "optimizers",
    subcategory: "power-optimizer",
    type: "DC Optimizer",
    power: "1300 W",
    price: 93.87,
    weight: 1.21,
    warranty: "25 years",
    protection: "IP68",
    certifications: ["IEC 62109-1", "IEC 62109-2"],
    description: "The MERC-1300-P is Huawei's latest generation DC power optimizer rated at 1300 W, featuring an extended input cable for maximum flexibility in complex roof layouts. It provides module-level MPPT tracking that eliminates mismatch losses from shading, soiling, or module degradation — recovering up to 30% more energy compared to non-optimized systems. The optimizer enables NEC 2017/2020 rapid shutdown compliance for enhanced safety, and transmits real-time module-level monitoring data via PLC communication to the inverter. IP68-rated and backed by a 25-year warranty, it is compatible with all Huawei SUN2000 string inverters and supports modules up to 650W.",
    features: ["Module-level MPPT", "Rapid shutdown", "Long input cable", "Compatible SUN2000"],
    stock: 100,
    minOrder: 10,
    seller: "QUALIWATT",
    image: "https://solar.huawei.com/admin/asset/v1/pro/view/7f9e836fa9b94b50bee12471a101b0bb.png",
    datasheet: "/datasheets/merc-1300-p.pdf",
  },

  // ═══════════════════════════════════════════
  // SMART DONGLES — Communication
  // ═══════════════════════════════════════════
  {
    id: "hw-sdongle-a05",
    sku: "SDongleA-05",
    name: "Huawei Smart Dongle A-05 (WiFi)",
    brand: "Huawei",
    category: "accessories",
    subcategory: "communication",
    type: "WiFi Dongle",
    price: 66.03,
    weight: 0.126,
    warranty: "5 years",
    certifications: ["CE"],
    description: "The Smart Dongle A-05 is a compact WiFi communication module that connects Huawei SUN2000 inverters to the FusionSolar cloud monitoring platform. It enables real-time energy production monitoring, remote fault diagnosis, automatic firmware updates, and performance analytics through the FusionSolar smartphone app and web portal. Plug-and-play installation via the inverter's COM port requires no additional wiring — simply insert and configure via the app. Supports 2.4 GHz WiFi with WPA2 encryption for secure data transmission. Essential for warranty activation and access to Huawei's AI-powered Smart I-V Curve Diagnosis feature.",
    features: ["WiFi communication", "FusionSolar App compatible", "Plug & Play"],
    stock: 30,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "https://solar.huawei.com/admin/asset/v1/pro/view/3f9c38a86253461c83bb4ff6c31346c8.png",
    datasheet: "/datasheets/sdongle-a05-wifi.pdf",
  },
  {
    id: "hw-sdongle-b06-eu",
    sku: "SDongleB-06-EU",
    name: "Huawei Smart Dongle B-06 EU (4G/LTE)",
    brand: "Huawei",
    category: "accessories",
    subcategory: "communication",
    type: "4G Dongle",
    price: 129.50,
    weight: 0.163,
    warranty: "5 years",
    certifications: ["CE", "RED"],
    description: "The Smart Dongle B-06 EU is a 4G/LTE communication module with integrated SIM card slot, designed for PV installations where WiFi connectivity is unavailable or unreliable. It provides the same full FusionSolar cloud integration as the WiFi variant — real-time monitoring, remote diagnostics, automatic firmware updates, and AI-powered performance optimization. The EU variant supports European 4G LTE bands (B1/B3/B7/B8/B20/B28) for broad network compatibility. Ideal for rural residential installations, agricultural buildings, and commercial rooftops without network infrastructure. Plug-and-play installation via the inverter's COM port with no external antenna required.",
    features: ["4G LTE communication", "SIM card slot", "FusionSolar App", "No WiFi needed"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "https://solar.huawei.com/admin/asset/v1/pro/view/3f9c38a86253461c83bb4ff6c31346c8.png",
    datasheet: "https://solar.huawei.com/fr/professionals/all-products/SDongleB-06",
    productPage: "https://solar.huawei.com/fr/professionals/all-products/SDongleB-06",
  },

  // ═══════════════════════════════════════════
  // EV CHARGERS
  // ═══════════════════════════════════════════
  {
    id: "hw-scharger-7ks-s0",
    sku: "SCharger-7KS-S0",
    name: "Huawei SCharger-7KS-S0 (7 kW)",
    brand: "Huawei",
    category: "ev-chargers",
    subcategory: "ac-charger",
    type: "AC Charger",
    power: "7 kW",
    price: 391.19,
    weight: 2,
    warranty: "5 years",
    protection: "IP65",
    certifications: ["IEC 61851-1", "IEC 62196-2"],
    description: "The SCharger-7KS-S0 is a 7 kW single-phase AC electric vehicle charger with Type 2 connector, engineered for residential solar-powered charging. Its intelligent Green Charging mode automatically adjusts charging power based on real-time PV surplus, maximizing solar self-consumption and minimizing grid electricity costs. Fully integrated with Huawei's FusionSolar ecosystem, it communicates directly with SUN2000 hybrid inverters for coordinated energy management. Supports scheduled charging for off-peak tariff optimization, RFID authentication for multi-user access control, and remote monitoring via the FusionSolar app. IP65-rated with a compact, sleek design for outdoor wall-mount installation.",
    features: ["Smart charging", "Solar surplus charging", "FusionSolar integration", "Type 2"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-scharger-7k.svg",
    datasheet: "/datasheets/scharger-series.pdf",
  },
  {
    id: "hw-scharger-22kt-s0",
    sku: "SCharger-22KT-S0",
    name: "Huawei SCharger-22KT-S0 (22 kW)",
    brand: "Huawei",
    category: "ev-chargers",
    subcategory: "ac-charger",
    type: "AC Charger 3-Phase",
    power: "22 kW",
    price: 414.58,
    weight: 2,
    warranty: "5 years",
    protection: "IP65",
    certifications: ["IEC 61851-1", "IEC 62196-2"],
    description: "The SCharger-22KT-S0 is a 22 kW three-phase AC electric vehicle charger delivering significantly faster charging speeds — up to 3x faster than single-phase 7 kW units. It features the same intelligent Green Charging mode for PV surplus optimization, dynamically adjusting between 6A and 32A per phase based on available solar power. The three-phase design is ideal for homes and businesses with three-phase grid connections, capable of adding approximately 120 km of range per hour of charging. Full FusionSolar integration enables coordinated operation with SUN2000 inverters, LUNA2000 batteries, and EMMA energy management. IP65-rated with Type 2 connector and RFID multi-user support.",
    features: ["22kW fast charging", "Smart solar surplus", "FusionSolar integration", "Type 2"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-scharger-22k.svg",
    datasheet: "/datasheets/scharger-series.pdf",
  },

  // ═══════════════════════════════════════════
  // SMART METERS & SENSORS
  // ═══════════════════════════════════════════
  {
    id: "hw-smartps-80ai-t0",
    sku: "SmartPS-80AI-T0",
    name: "Huawei SmartPS-80AI-T0 Three-Phase Sensor",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Sensor",
    price: 93.87,
    weight: 0.96,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11"],
    description: "The SmartPS-80AI-T0 is an AI-powered three-phase 80A smart power sensor that provides high-precision bidirectional energy measurement for Huawei solar installations. It continuously monitors grid export and import power, enabling the inverter to dynamically adjust output for zero-export compliance or maximum self-consumption. The integrated AI algorithm filters measurement noise for ±0.5% accuracy class, ensuring reliable operation even in electrically noisy environments. DIN rail mounted in the distribution board, it communicates with the inverter via RS485 for real-time power control response under 100ms. Required for all grid-connected Huawei residential installations to enable smart energy management.",
    features: ["80A rated current", "Three-phase", "AI powered", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smart-pwr-sensor.svg",
    datasheet: "/datasheets/smartps-80ai-t0.pdf",
  },
  {
    id: "hw-dtsu666-h250a",
    sku: "DTSU666-H250A/50mA",
    name: "Huawei DTSU666-H 250A/50mA Three-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Meter",
    price: 89.41,
    weight: 0,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11", "IEC 62053-21"],
    description: "The DTSU666-H 250A/50mA is a three-phase smart energy meter designed for commercial and industrial installations requiring high-current measurement via external current transformers (CTs). It measures up to 250A per phase through 50mA secondary CTs, providing Class 1 accuracy for billing-grade energy monitoring. RS485 communication enables real-time data transmission to Huawei inverters for dynamic export limitation and self-consumption optimization. The compact DIN rail design (4 modules wide) fits standard distribution boards, and the meter supports bidirectional measurement for accurate tracking of grid import, export, and self-consumed energy.",
    features: ["250A via CT", "Three-phase", "RS485 communication", "DIN rail"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-dtsu666-h.svg",
    datasheet: "https://solar.huawei.com/fr/professionals/all-products/DTSU666-H",
    productPage: "https://solar.huawei.com/fr/professionals/all-products/DTSU666-H",
  },
  {
    id: "hw-smartps-250a-t0",
    sku: "SmartPS-250A-T0",
    name: "Huawei SmartPS-250A-T0 Three-Phase Sensor",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Sensor",
    price: 89.41,
    weight: 1.5,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11"],
    description: "The SmartPS-250A-T0 is a three-phase 250A smart power sensor designed for high-current commercial and industrial Huawei solar installations. It provides direct 250A measurement without external CTs, simplifying installation while delivering high-precision bidirectional energy monitoring. RS485 communication enables sub-100ms power control response with the inverter for accurate zero-export operation and dynamic power curtailment. The compact DIN rail design integrates seamlessly into existing distribution boards. Ideal for commercial self-consumption systems, industrial rooftop installations, and sites requiring precise grid power management for feed-in tariff compliance.",
    features: ["250A rated current", "Three-phase", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smart-sensor-1000a.svg",
    datasheet: "/datasheets/smartps-250a-t0.pdf",
  },
  {
    id: "hw-smartps-100a-s0",
    sku: "SmartPS-100A-S0",
    name: "Huawei SmartPS-100A-S0 Single-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Single-Phase Smart Meter",
    price: 66.03,
    weight: 1.211,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11"],
    description: "The SmartPS-100A-S0 is a single-phase 100A smart power sensor for residential Huawei solar installations with single-phase grid connection. It provides high-precision bidirectional energy measurement at the grid connection point, enabling the inverter to dynamically control export power for grid compliance and maximize self-consumption. Direct 100A measurement eliminates the need for external current transformers, simplifying installation. RS485 communication delivers real-time power data to the inverter with sub-100ms response for accurate zero-export and load-following operation. Compact 2-module DIN rail design fits any residential distribution board.",
    features: ["100A rated", "Single-phase", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-smart-sensor-300a.svg",
    datasheet: "https://solar.huawei.com/fr/professionals/all-products/SmartPS-100A-S0",
    productPage: "https://solar.huawei.com/fr/professionals/all-products/SmartPS-100A-S0",
  },
  {
    id: "hw-ddsu666-h",
    sku: "DDSU666-H",
    name: "Huawei DDSU666-H Single-Phase Smart Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Single-Phase Smart Meter",
    price: 66.03,
    weight: 1.211,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11", "IEC 62053-21"],
    description: "The DDSU666-H is a single-phase smart energy meter providing Class 1 accuracy bidirectional power measurement for residential Huawei solar systems. It measures grid import and export power in real-time via RS485 communication, enabling the SUN2000 inverter to perform dynamic export limitation and self-consumption optimization. The meter supports active and reactive energy measurement with multi-tariff capability for time-of-use rate tracking. Compact 1-module DIN rail design for easy installation in residential distribution boards. Essential component for grid-connected single-phase systems requiring precise energy management and feed-in compliance.",
    features: ["Single-phase", "RS485", "DIN rail mount"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-ddsu666-h.svg",
    datasheet: "https://solar.huawei.com/fr/professionals/all-products/DDSU666-H",
    productPage: "https://solar.huawei.com/fr/professionals/all-products/DDSU666-H",
  },
  {
    id: "hw-dtsu666-h-100a",
    sku: "DTSU666-H-100A",
    name: "Huawei DTSU666-H 100A Three-Phase Meter",
    brand: "Huawei",
    category: "accessories",
    subcategory: "smart-meter",
    type: "Three-Phase Smart Meter",
    price: 93.87,
    weight: 1.211,
    warranty: "5 years",
    certifications: ["CE", "IEC 62052-11", "IEC 62053-21"],
    description: "The DTSU666-H 100A is a three-phase smart energy meter with direct 100A connection, designed for residential and small commercial Huawei solar installations with three-phase grid supply. It provides Class 1 bidirectional energy measurement for accurate tracking of grid import, export, and self-consumption. RS485 communication delivers real-time power data to the SUN2000 inverter for dynamic export control and load-following optimization. Supports active, reactive, and apparent energy measurement with multi-tariff time-of-use tracking. DIN rail mounted (4 modules wide) with built-in terminal covers for safe residential installation.",
    features: ["100A direct", "Three-phase", "RS485", "DIN rail"],
    stock: 10,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-dtsu666-h.svg",
    datasheet: "https://solar.huawei.com/fr/professionals/all-products/DTSU666-H",
    productPage: "https://solar.huawei.com/fr/professionals/all-products/DTSU666-H",
  },

  // ═══════════════════════════════════════════
  // BACKUP BOXES
  // ═══════════════════════════════════════════
  {
    id: "hw-smartguard-63a-s0",
    sku: "SmartGuard-63A-S0",
    name: "Huawei SmartGuard-63A-S0 Single Phase Backup Box",
    brand: "Huawei",
    category: "accessories",
    subcategory: "backup-box",
    type: "Backup Box Single Phase",
    power: "63A",
    price: 530.39,
    weight: 21.24,
    warranty: "10 years",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 60947-6-1"],
    description: "The SmartGuard-63A-S0 is a single-phase 63A automatic transfer switch (ATS) that enables whole-home backup power from LUNA2000 batteries during grid outages. It features ultra-fast <10ms switchover time — fast enough to keep sensitive electronics, networking equipment, and refrigeration running without interruption. The 63A rating supports total backup loads up to 14 kW, covering most residential single-phase needs. IP65-rated for indoor and outdoor installation with integrated surge protection and short-circuit safety. Works seamlessly with SUN2000 hybrid inverters, which continue solar charging of batteries even during grid outage for extended autonomy.",
    features: ["Automatic switchover <10ms", "Single phase", "63A rated", "Compatible LUNA2000"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "https://solar.huawei.com/admin/asset/v1/pro/view/d3a6abd7431648de84abc1eb9504a89b.png",
    datasheet: "https://solar.huawei.com/fr/professionals/all-products/SmartGuard-63A-S0",
    productPage: "https://solar.huawei.com/fr/professionals/all-products/SmartGuard-63A-S0",
  },
  {
    id: "hw-smartguard-63a-t0",
    sku: "SmartGuard-63A-T0",
    name: "Huawei SmartGuard-63A-T0 Three Phase Backup Box",
    brand: "Huawei",
    category: "accessories",
    subcategory: "backup-box",
    type: "Backup Box Three Phase",
    power: "63A",
    price: 709.68,
    weight: 25.1,
    warranty: "10 years",
    protection: "IP65",
    certifications: ["IEC 62109-1", "IEC 60947-6-1"],
    description: "The SmartGuard-63A-T0 is a three-phase 63A automatic transfer switch (ATS) providing whole-home backup power for three-phase residential installations with LUNA2000 battery storage. It detects grid failure within milliseconds and performs a seamless <10ms switchover to battery power, ensuring uninterrupted supply for all three phases. The 63A per phase rating supports backup loads up to 43 kW, covering even high-consumption homes with heat pumps, EV chargers, and air conditioning. IP65-rated for indoor/outdoor installation with comprehensive protection including surge, overcurrent, and short-circuit safety. The SUN2000 hybrid inverter continues PV charging during grid outage for maximum backup autonomy.",
    features: ["Automatic switchover <10ms", "Three phase", "63A rated", "Compatible LUNA2000"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "https://solar.huawei.com/admin/asset/v1/pro/view/d3a6abd7431648de84abc1eb9504a89b.png",
    datasheet: "/datasheets/smartguard-63a-t0.pdf",
  },

  // ═══════════════════════════════════════════
  // ENERGY MANAGEMENT
  // ═══════════════════════════════════════════
  {
    id: "hw-emma-a02",
    sku: "EMMA-A02",
    name: "Huawei EMMA-A02 Energy Management Assistant",
    brand: "Huawei",
    category: "accessories",
    subcategory: "energy-management",
    type: "Energy Management System",
    price: 317.70,
    weight: 1.25,
    warranty: "5 years",
    certifications: ["CE", "RED"],
    description: "The EMMA-A02 is Huawei's AI-powered Energy Management Assistant, the central intelligence unit that orchestrates all energy flows in a residential Huawei smart energy system. It connects to SUN2000 inverters, LUNA2000 batteries, SCharger EV chargers, and third-party heat pumps via SG-Ready to intelligently schedule loads based on PV production forecasts, electricity tariff windows, and household consumption patterns. The AI algorithm learns from historical data to predict optimal charge/discharge cycles, reducing grid dependency by up to 30% compared to standard self-consumption systems. Compact WiFi-connected device with DIN rail or wall mount options, managed entirely through the FusionSolar app with no additional subscription required.",
    features: ["AI-powered energy management", "Smart scheduling", "EV charger integration", "Heat pump control"],
    stock: 5,
    minOrder: 1,
    seller: "QUALIWATT",
    image: "/products/hw-emma-a02.svg",
    datasheet: "https://solar.huawei.com/fr/professionals/all-products/EMMA-A02",
    productPage: "https://solar.huawei.com/fr/professionals/all-products/EMMA-A02",
  },
];

// Category definitions for the catalog
export const CATEGORIES = [
  { id: "all", name: "Tous les produits", icon: "📦" },
  { id: "inverters", name: "Onduleurs", icon: "⚡" },
  { id: "batteries", name: "Stockage", icon: "🔋" },
  { id: "optimizers", name: "Optimiseurs", icon: "📈" },
  { id: "ev-chargers", name: "Bornes de recharge", icon: "🚗" },
  { id: "accessories", name: "Accessoires", icon: "🔧" },
];

// Helper functions
export const getProductsByCategory = (cat) =>
  cat === "all" ? PRODUCTS : PRODUCTS.filter(p => p.category === cat);

export const getProductById = (id) =>
  PRODUCTS.find(p => p.id === id);

export const searchProducts = (query) => {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.sku.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    (p.type && p.type.toLowerCase().includes(q))
  );
};

export const getProductCount = () => PRODUCTS.length;

export const getTotalStock = () =>
  PRODUCTS.reduce((sum, p) => sum + (p.stock || 0), 0);

export default PRODUCTS;
